# Generated by Django 3.2.16 on 2022-12-11 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221211_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.candidate'),
        ),
    ]
